import IcnArchiveSvg from "./icn-archive.svg";
import IcnAwardSvg from "./icn-award.svg";
import IcnBankSvg from "./icn-bank.svg";
import IcnBoltSvg from "./icn-bolt.svg";
import IcnChevronRightSvg from "./icn-chevron-right.svg";
import IcnCircleCheckSvg from "./icn-circle-check.svg";
import IcnCodeSvg from "./icn-code.svg";
import IcnCryptocurrencySvg from "./icn-cryptocurrency.svg";
import IcnDollarSignSvg from "./icn-dollar-sign.svg";
import IcnFacebookSvg from "./icn-facebook.svg";
import IcnFileSvg from "./icn-file.svg";
import IcnGlobeSvg from "./icn-globe.svg";
import IcnInstagramSvg from "./icn-instagram.svg";
import IcnLinkedinSvg from "./icn-linkedin.svg";
import IcnLockSvg from "./icn-lock.svg";
import IcnPullRequestSvg from "./icn-pull-request.svg";
import IcnSearchSvg from "./icn-search.svg";
import IcnSpeedometerSvg from "./icn-speedometer.svg";
import IcnStarSvg from "./icn-star.svg";
import IcnUsersSvg from "./icn-users.svg";
import IcnWindowSvg from "./icn-window.svg";
import IcnXSvg from "./icn-x.svg";

export const IcnArchive = IcnArchiveSvg;
export const IcnAward = IcnAwardSvg;
export const IcnBank = IcnBankSvg;
export const IcnBolt = IcnBoltSvg;
export const IcnChevronRight = IcnChevronRightSvg;
export const IcnCircleCheck = IcnCircleCheckSvg;
export const IcnCode = IcnCodeSvg;
export const IcnCryptocurrency = IcnCryptocurrencySvg;
export const IcnDollarSign = IcnDollarSignSvg;
export const IcnFacebook = IcnFacebookSvg;
export const IcnFile = IcnFileSvg;
export const IcnGlobe = IcnGlobeSvg;
export const IcnInstagram = IcnInstagramSvg;
export const IcnLinkedin = IcnLinkedinSvg;
export const IcnLock = IcnLockSvg;
export const IcnPullRequest = IcnPullRequestSvg;
export const IcnSearch = IcnSearchSvg;
export const IcnSpeedometer = IcnSpeedometerSvg;
export const IcnStar = IcnStarSvg;
export const IcnUsers = IcnUsersSvg;
export const IcnWindow = IcnWindowSvg;
export const IcnX = IcnXSvg;