import IcnArchiveSvg from "./icn-archive.svg";
import IcnArrowRightUpSvg from "./icn-arrow-up-right.svg";
import IcnAwardSvg from "./icn-award.svg";
import IcnBankSvg from "./icn-bank.svg";
import IcnBoltSvg from "./icn-bolt.svg";
import IcnBriefcaseSvg from "./icn-briefcase.svg";
import IcnBuildingSvg from "./icn-building.svg";
import IcnBuoySvg from "./icn-buoy.svg";
import IcnCalendarSvg from "./icn-calendar.svg";
import IcnChevronDownSvg from "./icn-chevron-down.svg";
import IcnChevronLeftSvg from "./icn-chevron-left.svg";
import IcnChevronRightSvg from "./icn-chevron-right.svg";
import IcnCircleCheckSvg from "./icn-circle-check.svg";
import IcnCircleHelpSvg from "./icn-circle-help.svg";
import IcnCircleMinusSvg from "./icn-circle-minus.svg";
import IcnClockSvg from "./icn-clock.svg";
import IcnCodeSvg from "./icn-code.svg";
import IcnCryptocurrencySvg from "./icn-cryptocurrency.svg";
import IcnDiamondSvg from "./icn-diamond.svg";
import IcnDollarSignSvg from "./icn-dollar-sign.svg";
import IcnFacebookSvg from "./icn-facebook.svg";
import IcnFileSvg from "./icn-file.svg";
import IcnFilterSvg from "./icn-filter.svg";
import IcnGlobeSvg from "./icn-globe.svg";
import IcnInstagramSvg from "./icn-instagram.svg";
import IcnLinkedinSvg from "./icn-linkedin.svg";
import IcnLockSvg from "./icn-lock.svg";
import IcnMailSvg from "./icn-mail.svg";
import IcnMapPinSvg from "./icn-map-pin.svg";
import IcnPullRequestSvg from "./icn-pull-request.svg";
import IcnSearchSvg from "./icn-search.svg";
import IcnShieldSvg from "./icn-shield.svg";
import IcnSpeedometerSvg from "./icn-speedometer.svg";
import IcnStarSvg from "./icn-star.svg";
import IcnThumbSvg from "./icn-thumb.svg";
import IcnTriangleSvg from "./icn-triangle.svg";
import IcnUsersSvg from "./icn-users.svg";
import IcnWindowSvg from "./icn-window.svg";
import IcnXSvg from "./icn-x.svg";

export const IcnArchive = IcnArchiveSvg;
export const IcnArrowUpRight = IcnArrowRightUpSvg;
export const IcnAward = IcnAwardSvg;
export const IcnBank = IcnBankSvg;
export const IcnBolt = IcnBoltSvg;
export const IcnBriefcase = IcnBriefcaseSvg;
export const IcnBuilding = IcnBuildingSvg;
export const IcnBuoy = IcnBuoySvg;
export const IcnCalendar = IcnCalendarSvg;
export const IcnChevronDown = IcnChevronDownSvg;
export const IcnChevronLeft = IcnChevronLeftSvg;
export const IcnChevronRight = IcnChevronRightSvg;
export const IcnCircleCheck = IcnCircleCheckSvg;
export const IcnCircleHelp = IcnCircleHelpSvg;
export const IcnCircleMinus = IcnCircleMinusSvg;
export const IcnClock = IcnClockSvg;
export const IcnCode = IcnCodeSvg;
export const IcnCryptocurrency = IcnCryptocurrencySvg;
export const IcnDiamond = IcnDiamondSvg;
export const IcnDollarSign = IcnDollarSignSvg;
export const IcnFacebook = IcnFacebookSvg;
export const IcnFile = IcnFileSvg;
export const IcnFilter = IcnFilterSvg;
export const IcnGlobe = IcnGlobeSvg;
export const IcnInstagram = IcnInstagramSvg;
export const IcnLinkedin = IcnLinkedinSvg;
export const IcnLock = IcnLockSvg;
export const IcnMail = IcnMailSvg;
export const IcnMapPin = IcnMapPinSvg;
export const IcnPullRequest = IcnPullRequestSvg;
export const IcnSearch = IcnSearchSvg;
export const IcnShield = IcnShieldSvg;
export const IcnSpeedometer = IcnSpeedometerSvg;
export const IcnStar = IcnStarSvg;
export const IcnThumb = IcnThumbSvg;
export const IcnTriangle = IcnTriangleSvg;
export const IcnUsers = IcnUsersSvg;
export const IcnWindow = IcnWindowSvg;
export const IcnX = IcnXSvg;