import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { NavigationBar } from "@/components/navigation/NavigationBar";
import { Footer } from "@/components/navigation/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <NavigationBar />
        <main>
          {children}
        </main> 
        <Footer />
      </body>
    </html>
  );
}
