import 'swiper/css';
import 'swiper/css/free-mode';
import "@/styles/index.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <div className="c-body-bg"/>
          {children}
      </body>
    </html>
  );
}
